============================= test session starts =============================
platform win32 -- Python 3.6.5, pytest-4.6.2, py-1.8.0, pluggy-0.12.0 -- C:\Users\Usuario\codenation\venv\Scripts\python.exe
cachedir: .pytest_cache
rootdir: C:\Users\Usuario\codenation\data-science-3
collecting ... collected 4 items

test_submit.py::test_q1 PASSED                                           [ 25%]
test_submit.py::test_q2 PASSED                                           [ 50%]
test_submit.py::test_q3 PASSED                                           [ 75%]
test_submit.py::test_q4 PASSED                                           [100%]

============================== warnings summary ===============================
C:\Users\Usuario\codenation\venv\lib\site-packages\sklearn\utils\validation.py:71
test_submit.py::test_q4
  C:\Users\Usuario\codenation\venv\lib\site-packages\sklearn\utils\validation.py:71: FutureWarning: Pass n_features_to_select=5 as keyword args. From version 0.25 passing these as positional arguments will result in an error
    FutureWarning)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
-- generated xml file: C:\Users\Usuario\codenation\data-science-3\output.xml --
==================== 4 passed, 2 warnings in 28.31 seconds ====================
